### ISSUE TITLE
All new illustrations / diagrams

### ISSUE THREAD

**Issue by shiffman** [shiffman/LearningProcessing#72]
i'm using this issue to keep track of any new or changed line drawings (not screenshots) that need to be created or fixed for 2nd edition:

numbering is from 150f3c272c0b23c7d776a15434f7e9ed render

* [x] 2.1 new Processing PDE window with sketched overlay
* [x] 2.5 new Processing PDE window with sketched overlay
* [x] 2.6 new Processing PDE window with sketched overlay
* [x] 4.5 circleX rethink this one?  also off in current render
* [ ] [OOP diagram in 8.3 writing the cookie cutter](https://github.com/shiffman/LearningProcessing/issues/19) needs to be fixed, also given a figure number?
* [x] 8.6 [new pass by value/ref diagram](https://github.com/shiffman/LearningProcessing/issues/19)! 
* [x] 18.10 -- array diagram
* [x] 18.11 -- associatve array diagram
* [x] 19.1, 19.2 -- these [need to be redone perhaps combined into one](https://github.com/shiffman/LearningProcessing/issues/65)?  

Finally, if it's not too much of a hassle this should be fixed for all illustrations:

* [x] [code style standards update](https://github.com/shiffman/LearningProcessing/issues/73)

**Comment by shiffman** [comment]
8.3 covered in separate issue.
